### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by brandonphelps** [colin-pm/grash#1]
I would recommend splitting up the install instructions such that if a consumer of the tool wanted to use it they would just use pip to install. This is pretty much the convention on python project repos. 
```
pip install grash
```
then they don't need to clone the repo down or have poetry installed.
you can then move the current install instructions into a "how to contribute" section.

**Comment by colin-pm** [comment]
Yeah, I will do that and close this issue once I have the package deployed on PyPi.  I wanted to leave that out of the docs until then.

- [ ] Add package to PyPi
