### ISSUE TITLE
README usage

### ISSUE THREAD

**Issue by brandonphelps** [colin-pm/grash#2]
For the usage, where its displaying what the deps of foo.sh and bar.sh, I'd recommend adding in what foo.sh and bar.sh are such that they generate the corresponding output.

**Comment by colin-pm** [comment]
I didn't want to get too deep in the details, but that seems like a good idea.  It would help demonstrate the tool within the readme.

**Comment by brandonphelps** [comment]
yeah, i find it helps a lot, being able to see the input and the output, the goal is having different ways of explaining the same thing. 
Can let people who learn thing in different ways absorb the information in the way that works best for them. However there is a balance to manage of not getting too detailed.
